### ISSUE TITLE
My creator credits...

### ISSUE THREAD

**Issue by Krash0** [tweakunwanted/OpenXC-Resellers#12]
Hello ..., it would be nice if you give me my credits as creator of the dashboard ... =)

I created this dashboard in 2018 ..., If you want to see the latest version 4.0 PREMIUM (up to 100% faster and improved) you can access: http://kofficepanel.com

Or contact me on WhatsApp: +55 48 996377413

**Comment by tweakunwanted** [comment]
You don't have proof of that. Also we don't recommend any solution that isn't self hosted. 

If anyone ends up here. Don't trust this guy

**Comment by Krash0** [comment]
Downloading my project, translating it into english and still sending it to github is a bit uneducated ...

I am the only person who actually has the source code for this old version (without being decrypted)

you can clearly see the difference between the decompiled code and my original code.

THE COMPILED CODE USES PHP ECHO TO PRINT ALL HTML !!!

I'M NOT WANTING ANYTHING, JUST SHIT MY CREDITS ON README.MD !!!

![image](https://user-images.githubusercontent.com/23028535/90063753-3b016480-dcc0-11ea-9161-5b9d68734506.png)


![image](https://user-images.githubusercontent.com/23028535/90063512-dfcf7200-dcbf-11ea-838e-fd733e8ec767.png)
